import os
from io import StringIO
from os.path import dirname
from tempfile import NamedTemporaryFile
from textwrap import dedent
from typing import Any
from PIL import Image

from lxml.etree import XML

from svglib.svglib import NodeTracker, svg2rlg


def drawing_from_svg(content: str) -> Any:
    """Convert a SVG string to a ReportLab Drawing."""
    return svg2rlg(StringIO(dedent(content)))  # type: ignore


def minimal_svg_node(content: str) -> NodeTracker:
    """Convert a minimal SVG snippet to a NodeTracker."""
    return NodeTracker(XML(content), None, 0, None, False)


def svg_raster_difference(svg: str, raster: str, scale=1, tolerance=3) -> float:
    """
        Calculates the percentage difference between the raster generated by
        svglib/reportlab and a reference raster.

        Avoid using large images since everything is loaded into memory.

        This needs a renderPM backend to rasterize the svg drawing.

        Args:
            svg: The svg file path from the test samples directory.
            raster: The raster file path from the test samples directory.
            scale: The amount to scale the svg. Use 4/3 to match with pixels.
            tolerance: The maximum color difference between the two pixels.

        Returns:
            The percentage of pixels that were different.
            100 is completely different
            0 is exactly the same within tolerance
    """
    test_root = dirname(__file__)
    svg_path = os.path.join(test_root, 'samples', svg)
    raster_path = os.path.join(test_root, "samples", raster)
    
    assert os.path.exists(svg_path)
    assert os.path.exists(raster_path)
    
    svg_file = open(svg_path, 'rb')
    raster_file = open(raster_path, "rb")
    
    drawing = svg2rlg(svg_file)
    if scale and scale != 1:
        drawing.width *= scale
        drawing.height *= scale
        drawing.scale(scale, scale)

    temp_name = None
    with NamedTemporaryFile(mode="w", suffix=".png", delete=False) as temp:
        temp_name = temp.name

    assert temp_name is not None

    drawing.save(formats=['png'], outDir=None, fnRoot=temp_name)

    incorrect_pixels = 0
    squared_tolerance = tolerance * tolerance
    max_pixels = 1
    with Image.open(raster_file) as raster:
        with Image.open(temp_name) as drawing_raster:
            assert raster.size == drawing_raster.size

            # Convert RGB to match the reportlab export
            p1 = raster.convert('RGB').load()
            p2 = drawing_raster.convert('RGB').load()

            width, height = raster.size
            max_pixels = width * height
            for y in range(height):
                for x in range(width):
                    r1, g1, b1 = p1[x, y]
                    r2, g2, b2 = p2[x, y]

                    dr = r1 - r2
                    dg = g1 - g2
                    db = b1 - b2

                    # Check if the squared difference between the color is greater
                    # than the tolerance
                    squared_distance = dr * dr + dg * dg + db * db
                    if squared_distance > squared_tolerance:
                        incorrect_pixels += 1

    os.unlink(temp_name)

    return (incorrect_pixels / max_pixels) * 100


