name: Run Matrix Tests on MacOS
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on MacOs"
    runs-on: "macos-latest"
    strategy:
      matrix:
        python-version: ["3.9", "3.13", "pypy-3.9"]
    steps:
      - uses: "actions/checkout@v4"

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Setup Cairo
        run: |
          brew install cairo pkg-config libxml2 libxslt jpeg

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create Virtual Environment
        run: uv venv

      - name: "Cache for wikipedia flags"
        uses: actions/cache@v3
        env:
          cache-name: "cache-wikipedia-flags"
        with:
          path: "tests/samples/wikipedia/flags"
          key: "wikipedia-flags-${{ matrix.python-version }}-${{ matrix.os }}"
      - name: "Cache for wikipedia symbols"
        uses: actions/cache@v3
        env:
          cache-name: "cache-wikipedia-symbols"
        with:
          path: "tests/samples/wikipedia/symbols"
          key: "wikipedia-symbols-${{ matrix.python-version }}-${{ matrix.os }}"
      - name: "Cache for w3c svg12 tinytestsuite"
        uses: actions/cache@v3
        env:
          cache-name: "cache-w3c-svg12-tinytestsuite"
        with:
          path: "tests/samples/W3C_SVG_12_TinyTestSuite"
          key: "w3c-svg12-tinytestsuite-${{ matrix.python-version }}-${{ matrix.os }}"
      - name: "Install dependencies"
        run: uv pip install -e .[dev]

      - name: "Run tests for ${{ matrix.python-version }}"
        run: uv run pytest
